Improved functions: usage, reset-services, added line number toggle in vim

diff --git a/myvars b/myvars
--- a/myvars
+++ b/myvars
@@ -3,10 +3,12 @@ HOMEDIR=/home/$HOSTNAME
 cd $HOMEDIR
 readarray -t applist < <(ls -l $HOMEDIR/| awk '/^d/ {print $NF}')
 
-mkdir /var/cw/systeam/.vim-backup > /dev/null 2>&1
+[[ -d /var/cw/systeam/.vim-backup ]] || mkdir /var/cw/systeam/.vim-backup > /dev/null 2>&1
 cat <<- _EOF_ > /root/.vimrc
 set pastetoggle=<F3>
-set number
+nnoremap <F4> :set number!<CR>
+syntax on
+filetype on
 set backup
 set backupdir=/var/cw/systeam/.vim-backup
 set writebackup
@@ -239,14 +241,23 @@ else
 fi
         }
 
-reset-services () {
-    systemctl restart nginx
-    systemctl restart varnish
-    systemctl restart apache2
-    systemctl restart $(php -v | awk '{print "php"substr($2,1,3)"-fpm";exit}')
-    systemctl restart mysql
-    systemctl restart memcached
-    systemctl restart redis-server
+reset-services () { 
+    services=("nginx" "varnish" "apache2" "php-fpm" "mysql" "memcached" "redis-server")
+
+    for service in "${services[@]}"; do
+        if [[ $service == "php-fpm" ]]; then
+            service=$(php -v | awk '{print "php"substr($2,1,3)"-fpm";exit}')
+        fi
+
+        echo "Restarting $service..."
+        if systemctl restart $service; then
+            echo "Successfully restarted: $(tput bold)$(tput setaf 1)$service: $(tput sgr0)."
+        else
+            echo "Failed to restart: $(tput bold)$(tput setaf 1)$service: $(tput sgr0)."
+            echo "Latest logs:"
+            journalctl -u $service -n 10 --no-pager | grep -v '^-- Logs begin'
+        fi
+    done
 }
 
 status-services () {
@@ -273,28 +284,52 @@ status-services () {
 }
 
 usage () {
-    echo "$(tput bold)$(tput setaf 1)Nginx:$(tput sgr0)"
-    systemctl status nginx | awk '/Tasks|Memory/ {print $0}'
-        
-    echo "$(tput bold)$(tput setaf 1)Varnish:$(tput sgr0)"
-    systemctl status varnish | awk '/Tasks|Memory/ {print $0}'
-        
-    echo "$(tput bold)$(tput setaf 1)Apache:$(tput sgr0)"
-    systemctl status apache2 | awk '/Tasks|Memory/ {print $0}'
-        
-    echo "$(tput bold)$(tput setaf 1)PHP-FPM:$(tput sgr0)"
-    systemctl status $(php -v | awk '{print "php"substr($2,1,3)"-fpm";exit}') | awk '/Tasks|Memory/ {print $0}'
-        
-    echo "$(tput bold)$(tput setaf 1)MySQL/MariaDB:$(tput sgr0)"
-    systemctl status mysql | awk '/Tasks|Memory/ {print $0}'
-        
-    echo "$(tput bold)$(tput setaf 1)Memcache:$(tput sgr0)"
-    systemctl status memcached | awk '/Tasks|Memory/ {print $0}'
-        
-    echo "$(tput bold)$(tput setaf 1)Redis:$(tput sgr0)"
-    ( systemctl status redis-server | awk '/Tasks|Memory/ {print $0}' ) 2> /dev/null
-}
+  get_all_descendant_pids() {
+    local parent_pid=$1
+    local child_pids=$(pgrep -P $parent_pid)
 
+    for child_pid in $child_pids; do
+      get_all_descendant_pids $child_pid
+    done
+
+    echo $child_pids
+  }
+
+  services=("nginx" "varnish" "apache2" "php-fpm" "mysql" "memcached" "redis-server")
+  
+  for service in "${services[@]}"; do
+    if [[ $service == "php-fpm" ]]; then
+      service=$(php -v | awk '{print "php"substr($2,1,3)"-fpm";exit}')
+    fi
+    main_pid=$(systemctl show -p MainPID $service 2>/dev/null | cut -d= -f2)
+    
+    if [ -n "$main_pid" -a -e "/proc/$main_pid" ]; then
+      all_pids="$main_pid $(get_all_descendant_pids $main_pid)"
+      total_files=0
+      total_cpu=0.0
+
+      for pid in $all_pids; do
+        if [ -n "$pid" -a -e "/proc/$pid" ]; then
+          num_files=$(lsof -p $pid 2>/dev/null | wc -l)
+          cpu=$(ps -p $pid -o %cpu= 2>/dev/null)
+          
+          if [ $? -eq 0 -a -n "$cpu" ]; then
+            total_files=$((total_files + num_files))
+            total_cpu=$(echo "$total_cpu + $cpu" | bc)
+          fi
+        fi
+      done
+      
+      
+      echo "$(tput bold)$(tput setaf 1)$service: $(tput sgr0)"
+      systemctl status $service | awk '/Tasks|Memory/ {print $0}'
+      echo "Open Files: $total_files"
+      echo "Total CPU Usage: $total_cpu%"
+    else
+      echo "$(tput bold)$(tput setaf 1)$service: $(tput sgr0)Not running"
+    fi
+  done
+}
 
 sqlvars () {
 	mysqladmin variables | tr -d " " | awk -F'|' '{print $2 " = " $3}'
